# Generated by Django 4.2 on 2023-05-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionfisica',
            name='ubiLocker',
            field=models.SmallIntegerField(db_comment='Número de locker: 1,2,3,4..', null=True),
        ),
    ]
