# Generated by Django 4.2 on 2023-10-03 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamaterial',
            name='entFechaHora',
            field=models.DateTimeField(db_comment='Fecha y hora que entregan los elementos', default=datetime.datetime(2023, 10, 3, 23, 33, 32, 488702, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ubicacionfisica',
            name='ubiDeposito',
            field=models.CharField(db_comment='Número de bodega: 1,2,3,4..', max_length=50),
        ),
        migrations.AlterField(
            model_name='ubicacionfisica',
            name='ubiEntrepano',
            field=models.CharField(db_comment='Número de Entrepaño: 1,2,3,4..', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionfisica',
            name='ubiEstante',
            field=models.CharField(db_comment='Número de bodega: 1,2,3,4..', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionfisica',
            name='ubiLocker',
            field=models.CharField(db_comment='Número de locker: 1,2,3,4..', max_length=50, null=True),
        ),
    ]
