# Generated by Django 4.2 on 2023-05-23 22:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appGestionInventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallesolicitud",
            name="detUnidadMedida",
            field=models.ForeignKey(
                db_comment="Unidad de médida del elemento que se requeire",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="appGestionInventario.unidadmedida",
            ),
        ),
        migrations.AlterField(
            model_name="entradamaterial",
            name="entFechaHora",
            field=models.DateTimeField(
                db_comment="Fecha y hora que entregan los elementos",
                default=datetime.datetime(
                    2023, 5, 23, 22, 56, 31, 600312, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
