# Generated by Django 4.2 on 2023-05-25 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0002_alter_detallesolicitud_detunidadmedida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamaterial',
            name='entFechaHora',
            field=models.DateTimeField(db_comment='Fecha y hora que entregan los elementos', default=datetime.datetime(2023, 5, 25, 15, 47, 46, 132779, tzinfo=datetime.timezone.utc)),
        ),
    ]
